spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cskaoyanmall
    username: root
    password: 123456
  mvc:
    static-path-pattern: /pic/**
  resources:
    static-locations: file:d:/file/proPic/
  jackson:
    #指定日期格式，比如yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd HH:mm:ss
    #指定日期格式化时区
    time-zone: GMT+8
server:
  port: 8083
pagehelper:
  helper-dialect: mysql
logging:
  level:
    com.cskaoyan.mall.mapper: debug
    com.cskaoyan.mall.service: error
file:
  #注意要使用起来就得先按照路径创建好文件夹
  url: d:/file/proPic/

mybatis:
  type-handlers-package: com.cskaoyan.mall.typehandler
aliyun:
  accessKeyId: LTAI4Fr5gfYhcVjLMqeRGbuT
  accessKeySecret: IrkcHu6dZyrjPZRushgO76P5392HJ1
  oss:
    bucket: cskaoyan
    endPoint: oss-cn-beijing.aliyuncs.com
  sms:
    signName: stone4j
    templateCode: SMS_173765187