spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cskaoyanmall?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 3group
  mvc:
    static-path-pattern: /pic/**
  resources:
    static-locations: file:c:/Users/24039/Pictures/pic/
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  port: 8081
pagehelper:
  helper-dialect: mysql
logging:
  level:
    com.cskaoyan.mall.mapper: debug
    com.cskaoyan.mall.service: error
file:
  url: c:/Users/24039/Pictures/pic/
mybatis:
  type-handlers-package: com.cskaoyan.mall.typehandler
aliyun:
  accessKeyId: LTAI4Fr5gfYhcVjLMqeRGbuT
  accessKeySecret: IrkcHu6dZyrjPZRushgO76P5392HJ1
  oss:
    bucket: cskaoyan
    endPoint: oss-cn-beijing.aliyuncs.com
  sms:
    signName: stone4j
    templateCode: SMS_173765187
